version: "3.7"

services:
  favemarx_frontend:
    depends_on:
      - favemarx_db
    build:
      context: ./
      dockerfile: ./frontend/Dockerfile
    ports:
      - 80:80
      - 443:443

  favemarx_backend:
    depends_on:
      - favemarx_db
    build:
      context: ./
      dockerfile: ./backend/Dockerfile
    ports:
      - 8080:80
      - 4430:443

  favemarx_db:
    build:
      context: ./
      dockerfile: ./database/mysql.dockerfile
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password