version: "3.7"

services:
  favemarx:
    depends_on:
      - favemarx_db
    build:
      context: ./
      dockerfile: nodejs.dockerfile
    ports:
      - 80:8080
      - 443:8443
    #environment:

  favemarx_db:
    build:
      context: ./
      dockerfile: mysql.dockerfile
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password