version: "3.7"

services:
  favemarx_local:
    depends_on:
      - favemarx_db
    build:
      context: ./
      dockerfile: nodejs.local.dockerfile
    ports:
      - 80:80
      - 443:443
    profiles:
      - local

  favemarx_prod:
    depends_on:
      - favemarx_db
    build:
      context: ./
      dockerfile: nodejs.prod.dockerfile
    ports:
      - 80:80
      - 443:443
    profiles:
      - prod

  favemarx_db:
    build:
      context: ./
      dockerfile: mysql.dockerfile
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password